### ISSUE TITLE
advice on where to incorporate freesurfer manual fixes 

### ISSUE THREAD

**Issue by cmpetty** [Washington-University/HCPpipelines#85] opened 2018-12-12 15:42 UTC
I am going through subjects' freesurfer results and doing manual fixes like control points since its doing a poor job in the temporal pole area.

I added a specific controlPoints processing script in place of "FreeSurfer/FreeSurferPipeline.sh" that picks up with "-autorecon2-cp" and runs all the same steps afterwards.

`
recon-all -subjid $SubjectID -sd $SubjectDIR -autorecon2-cp -nosmooth2 -noinflate2 -nocurvstats -nosegstats -openmp ${num_cores} ${seed_cmd_appendix}
`

Any suggestions where else i will need to make changes to have these changes be effective for the rest of the Freesurfer/PostFreesurfer pipeline?

I can see that my control.dat was picked up in the normal processing stream, but it didn't seem to have much affect on anything after that.

This is after running from -autorecon2-cp on:
![image](https://user-images.githubusercontent.com/2243287/49880418-1d4c6f80-fdfa-11e8-8dd6-46832c49036a.png)

**Comment by mharms** [comment] 2018-12-14 17:00
Are you saying that you confirmed that in the recon-all.log, for both the Normalization1 and Normalization2 stages, that the call to 'mri_normalize' included "-f $subjdir/tmp/control.dat"?  If that was included, then I'd say that your control points simply didn't have the intended effect.

**Comment by mharms** [comment] 2018-12-14 17:39
I see that FreeSurferHiresWhite.sh involves the use of a control.hires.dat file.  So, to get CPs to work properly in the context of the current HCPpipelines (written around using FS 5.3-HCP), you are probably going to need to revise that code as well.

@glasserm Why was the use of a control.hires.dat file (containing the center of gravity of the left and right hemi WM) necessary, given that control points (-f flag) are an optional input to mri_normalize?

More generally, when we switch to FS 6.0, edits should become easier to implement, since we will be using FS in a more "native" state (without the jumping in and out of various recon-all stages).

**Comment by cmpetty** [comment] 2018-12-14 20:48
i added a HCPpipelines-3.27.0/FreeSurfer/FreeSurferPipeline_controlPoints.sh script that picks up the freesurfer processing and includes "-autorecon2-cp" and everything after.

i added a FreeSurferHiresWhite_controlPoints.sh call in there, that detects if there is "tmp/control.dat" that i would typically use for control points.  If it exists, i convert those to the hires space and save them as control.hires.dat and use that file instead of the 2 standard center of gravity WM points from above.

**Comment by glasserm** [comment] 2018-12-14 21:50
Bruce said it needed to be written that way.

**Comment by mharms** [comment] 2018-12-14 22:20
That doesn't make sense to me.  mri_normalize doesn't _need_ to have a control points file, unless there is something about the use of the -surface flag that requires it in that particular situation.

**Comment by mharms** [comment] 2019-05-31 18:53
Closing this issue.  The HCPpipelines, as of version 4.0.0, should now support the capability to make common FreeSurfer edits in the context of FS 6.0.0.

**Closed by mharms** 2019-05-31 18:53 UTC
