### ISSUE TITLE
Possible bug in GenericfMRIVolumeProcessingPipelineBatch.7T.sh

### ISSUE THREAD

**Issue by roeysc** [Washington-University/HCPpipelines#130] opened 2019-09-11 07:46 UTC
Hi everyone,

I think there might be a potential bug in setting the phase encoding direction in 
GenericfMRIVolumeProcessingPipelineBatch.7T.sh.

Currently, the phase encoding direction is extracted like so:
PhaseEncodingDir=${fMRIName:start:2}

But I believe it should be as follows:
PhaseEncodingDir=${fMRIName:end-2:2}
as the fMRINames end (and don't start) with "AP" or "PA".

Best,
Roey

**Comment by mharms** [comment] 2019-09-11 13:19
The full section of relevant code is:
```
		len=${#fMRIName}
		echo "  ${SCRIPT_NAME}: len: $len"
		start=$(( len - 2 ))
		
		PhaseEncodingDir=${fMRIName:start:2}
```
so I don't see a problem here.  I'm closing this.  If you still think this is a problem, please re-open.

**Closed by mharms** 2019-09-11 13:19 UTC

**Comment by coalsont** [comment] 2019-09-11 20:07
The choice of variable name is somewhat unfortunate, as it looks like a keyword in the style of matlab indexing.  In reality, "start" and "end" aren't keywords, but bash treats undefined variables as having a value equal to 0 in this context (and without `set -u`), and negative indices are accepted as counting backwards from the end, so "start+2" and "end-3" result in what is intuitively expected from keywords, as long as "start" and "end" are unset.

However, `${myvar:-2:2}` doesn't work, because of an unfortunate syntax overlap with default substitution, so the most succinct way to take the last 2 letters this is probably this (as specifying a length of 2 is superfluous if they are the last 2 letters):

```
tim@timsdev:~$ myvar=test
tim@timsdev:~$ echo ${myvar:(-2)}
st
```

I'm not sure what the clearest way is, I find bash parameter expansion operators to be rather arcane.

**Comment by coalsont** [comment] 2019-09-11 20:14
Okay, so you can use a space instead of parenthesis, but using syntax that depends on whitespace sounds like trouble:

```
tim@timsdev:~$ myvar=test
tim@timsdev:~$ echo ${myvar: -2}
st
tim@timsdev:~$ echo ${myvar:-2}
test
```

**Comment by mharms** [comment] 2019-09-11 20:59
@coalsont Did you see my response to this earlier today?  In particular, `start` is NOT an undefined variable.  It is defined in the immediately preceding lines of code. A quick token example in a bash shell shows that this works just as intended:

```
[mharms@harmsmac]$ tmp=abcdefgh
[mharms@harmsmac]$ len=${#tmp}
[mharms@harmsmac]$ echo $len
8
[mharms@harmsmac]$ start=$(( len - 2 ))
[mharms@harmsmac]$ echo $start
6
[mharms@harmsmac]$ tmp2=${tmp:start:2}
[mharms@harmsmac]$ echo $tmp2
gh
```

**Comment by coalsont** [comment] 2019-09-11 21:05
Yes, I saw your comment, and I didn't reopen the bug, because the current code works.  I was explaining to @roeysc why the code did something other than what he expected, and how bash could have tricked him into thinking "start" and "end" were keywords, when they aren't.

**Comment by roeysc** [comment] 2019-09-12 06:11
@coalsont and @mharms, thank you both for you clarification (that was indeed the source of my mistake).
