### ISSUE TITLE
Renamed issue: Subject 204218 resting state detrending failed

### ISSUE THREAD

**Issue by mharms** [Washington-University/HCPpipelines#107] opened 2019-04-23 03:11 UTC
## Please use issue #108 for the original topic of `hcp_fix` without motion regression, and `fix` argument parsing.

**Background**: In the v4.0.0 HCPpipelines version of `ICAFIX/hcp_fix`, we added the capability to control whether the motion parameters were regressed out of the data as part of the fix-cleaning (via the `do_motion_regression` argument).  [Prior to that (e.g., v3.27.0 and earlier), regression of the motion parameters was always applied].

FIX was originally written for volume (NIFTI) data, with the assumption that any high-pass filtering was applied _prior_ to FIX itself.  Thus, FIX originally only needed to worry about applying the same hp filter to the motion regressors, and thus in the `fix` script, the `-h` argument (to specify the filter) was made a subargument to the `-m` flag (that instructs `fix` to apply motion regression).

When the CIFTI format came along, the hp filtering of the CIFTI dtseries data was implemented in the context of `fix_3_clean` (called by the `fix` script to implement the actual cleaning of the data).  But the `-h` argument in `fix` stayed a subargument to the `-m` flag.

**Problem**:  While `fix_3_clean` has the capability to  independently apply motion regression and an hp filter to the CIFTI dtseries, the `fix` script itself does not support that -- unless one requests motion regression, there is no mechanism in `fix` itself for filtering the dtseries.

Consequently, if running the v4.0.0 version of `hcp_fix` with something like the following
`hcp_fix <data> 2000 FALSE`
the volume (NIFTI) data will be filtered by the requested hp=2000 filter (since that is done in `hcp_fix` script itself), but the CIFTI dtseries data will not get filtered at all (due to the setting of `FALSE` for the `do_motion_regression` argument).  Insidiously in this situation, a cleaned CIFTI file will still be generated, and the file name will in fact be labeled `hp2000_clean.dtseries.nii`, even though an hp=2000 filter wasn't actually applied to it!!

**Suggested solution:**  Split `-m` and `-h` into independent arguments in the `fix` script.  (Ideally, in the FIX distribution itself).

**Comment by kjamison** [comment] 2019-04-23 17:21
I just noticed evidence of the opposite problem in subject 204218. The
hp2000_clean.nii.gz NIFTI files have a significant linear trend, but the
hp2000_clean.dtseries.nii CIFTI do not have this trend. See attached
figures showing this issue for both REST1_LR and REST1_RL for 204218. It's
not all subjects though, since I tested this in one other subject, 102311,
and both NIFTI and CIFTI appear to have NO linear trend.

(Note I did remove the overall mean for each voxel timecourse before
plotting, and for the NIFTI I'm only showing gray matter voxels)

-Keith

**Comment by kjamison** [comment] 2019-04-23 17:53
Here are the figures mentioned in the previous reply:
<img width="818" alt="hcp_hp2000_nifti_cifti_204218_rfMRI_REST1_RL" src="https://user-images.githubusercontent.com/8633495/56604015-02231500-65cf-11e9-819c-2dbf6c45b1dd.png">
<img width="669" alt="hcp_hp2000_nifti_cifti_204218_rfMRI_REST1_LR" src="https://user-images.githubusercontent.com/8633495/56604016-02231500-65cf-11e9-83e8-7eb4c1ba8994.png">
<img width="885" alt="hcp_hp2000_nifti_cifti_102311_rfMRI_REST1_LR" src="https://user-images.githubusercontent.com/8633495/56604023-064f3280-65cf-11e9-8490-b911eebb81e6.png">

**Comment by mharms** [comment] 2019-04-23 18:17
How did you select the "gray matter voxels" for the NIFTI?  What if you compute the mean time course for the NIFTI using all non-zero voxels?

**Comment by kjamison** [comment] 2019-04-23 18:43
I selected them based on a downsampled aparc+aseg.nii.gz, excluding labels for WM,CSF, ventricles, and a few misc. Tried with all non-zero voxels and the linear trend is still there.

**Comment by coalsont** [comment] 2019-04-23 18:51
Isn't the detrending supposed to regress each voxel/vertex timeseries separately anyway?  Those plots obviously have some voxels increasing over time, and others decreasing.

**Comment by kjamison** [comment] 2019-04-23 20:15
Right you can see the trend in the individual voxels in either case. Just to test, I ran fslmaths-based filtering again on this hp2000_clean.nii.gz file and it definitely removes the linear trend:
`fslmaths rfMRI_REST1_LR_hp2000_clean -bptf 1388.888889 -1 rfMRI_REST1_LR_hp2000_clean_hp2000`
<img width="857" alt="hcp_hp2000_nifti_cifti_204218_rfMRI_REST1_LR_filteragain" src="https://user-images.githubusercontent.com/8633495/56612628-d7db5280-65e2-11e9-9a66-217deb25002f.png">

**Comment by coalsont** [comment] 2019-04-23 20:30
We should definitely figure out what happened with that subject, but this issue was intended to be about a problem with fix's argument parsing.  If you have more to say about the problem in this individual, please start a new issue, or use the hcp-users list, or...

**Comment by coalsont** [comment] 2019-04-23 20:33
Actually, maybe I should just make a new issue for the original topic, since all of the replies are about the problem in the individual.

**Comment by kjamison** [comment] 2019-04-23 20:59
I just sent this message to the hcp-users list

**Comment by kjamison** [comment] 2019-04-23 21:00
Oops I just hit the wrong button and accidentally closed this. Reopening in case this is the preferred location for handling this issue.

**Comment by mharms** [comment] 2019-04-23 21:17
204218 happens to be one of the subjects for which we applied manual reclassification of the FIX output, and I strongly suspect that is related to what you found in this subject/run.  I tracked down our internal copy of hp2000_clean.nii.gz following the original run of FIX (`hcp_fix`) and its mean time course doesn't have any such linear trend.

This is therefore unrelated to this particular Issue that I opened, but does suggest a possible bug in `ReApplyFixPipeline.sh` (or at least the version of that script in place at the time of HCP-YA).  If you want to pursue this, I suggest you create a separate issue where the discussion can continue.

**Comment by coalsont** [comment] 2019-04-23 21:24
@mharms: since all the replies here are about this, I renamed this issue, so discussion can continue here if desired.  See #108.  This can be reversed, but it seems less of a hassle this way.

@kjamison: what release of the data are you using?  We should probably track down what other subjects might be impacted.

**Comment by mharms** [comment] 2019-04-23 21:25
I see that @coalsont renamed this Issue, and restarted the original issue as #108.  That's fine with me.
@tbbrown : Exactly which version of the HCPpipelines and FIX was used for running the "ReApplyFix" resource (`204218_3T/RESOURCES/rfMRI_REST1_RL_ReApplyFix`) following the application of the "ApplyHandReClassification" resource?

**Comment by glasserm** [comment] 2019-04-24 00:50
In

https://github.com/Washington-University/HCPpipelines/blob/master/ICAFIX/ReApplyFixPipeline.sh:

Change Line 416: 

$FSLDIR/bin/imln ../$fMRIName filtered_func_data

to

$FSLDIR/bin/imln ../${fMRIName}_hp${hp} filtered_func_data

I seem to have forgotten that fix_3_clean.m does not highpass filter volume data or that $fmri variable in hcp_fix changes to include the highpass string after the data are highpassed.

**Comment by mharms** [comment] 2019-04-24 12:39
The following is preferable, since it also controls for the hp=-1 condition:

`$FSLDIR/bin/imln ../${fMRIName}${hpStr} filtered_func_data`

`hpStr` is defined at L369.

FWIW, in our version of `hcp_fix` we now define a `fmrihp` variable to make clear that it includes the highpass string.

**Comment by glasserm** [comment] 2019-04-24 12:59
Ok

**Comment by tbbrown** [comment] 2019-04-24 15:41
In reply to @mharms question about the exact version of HCP Pipelines in use for running ReApplyFix, the processing log file shows it was version v3.22.0-beta.5 of the HCP Pipelines. It may take a bit of detective work to determine the exact version of FIX in use at the time. If that detective work is necessary/desirable let me know, and I'll devote some time to it.

**Comment by mharms** [comment] 2019-04-24 15:58
No need.  Per above, the bug has been identified, and it exists in the v4.0.0 pipeline version, so it very likely existed in all previous versions as well.

**Comment by glasserm** [comment] 2019-04-24 16:04
Please see my HCP users email.

**Comment by kjamison** [comment] 2019-04-24 16:24
Am I correct in assuming the linear trend in the volume inputs to
ReApplyFix means the actual nuisance and ICA component regression and
cleaning won't be correct for these scans either? That is, beyond just
having a linear trend in the outputs, they aren't actually being denoised
properly?

-Keith

**Comment by mharms** [comment] 2019-04-24 16:59
`ReApplyFixPipeline.sh` does NOT actually re-run melodic.  It's purpose in the case of manual component reclassification is simply to re-clean the data.  So, NO, the only thing that should be wrong in this case is that the nuisance (motion regressors) and noise component regression was applied to the _non-filtered_ volume (NIFTI) data, rather than the hp-filtered volume data.  Incidentally, the CIFTI data (hp2000_clean.dtseries.nii) should be fine as well (since the hp-filtering of that occurs inside `fix_3_clean.m`).   [And that is in fact consistent with the pictures you showed, since the CIFTI data doesn't have a linear trend].

**Comment by glasserm** [comment] 2019-04-25 00:26
The noise removal in the volume data will poor because the regressions will not fit if there is a linear trend in the volume data.

**Closed** 2019-05-31 18:48 UTC
