### ISSUE TITLE
ICAFixProcessing Batch error

### ISSUE THREAD

**Issue by betsy1226** [Washington-University/HCPpipelines#272] opened 2023-07-22 14:59 UTC
I am trying to run IcaFixProcessingBatch.sh but it returned:
Sat Jul 22 13:28:31 CST 2023:hcp_fix: HCPPIPEDIR: /usr/local/HCPpipelines
Sat Jul 22 13:28:31 CST 2023:hcp_fix: FSLDIR: /usr/local/fsl
Sat Jul 22 13:28:31 CST 2023:hcp_fix: FSL_FIXDIR: /usr/local/fix
Sat Jul 22 13:28:31 CST 2023:hcp_fix: Sourcing /usr/local/fix/settings.sh
Sat Jul 22 13:28:31 CST 2023:hcp_fix: Showing HCP Pipelines version
v4.7.0
Sat Jul 22 13:28:31 CST 2023:hcp_fix: Showing FSL version
Sat Jul 22 13:28:31 CST 2023:hcp_fix: INFO: Determined that the FSL version in use is 6.0.6.5
Sat Jul 22 13:28:31 CST 2023:hcp_fix: FSL version: 6.0.6.5
Sat Jul 22 13:28:31 CST 2023:hcp_fix: FIX version: 1.06.15
Sat Jul 22 13:28:31 CST 2023:hcp_fix: FSL_FIX_MATLAB_MODE: 0
Sat Jul 22 13:28:31 CST 2023:hcp_fix: fMRI Name: rfMRI_REST1_LR
Sat Jul 22 13:28:31 CST 2023:hcp_fix: highpass: 2000
Sat Jul 22 13:28:31 CST 2023:hcp_fix: doMotionRegression: TRUE
Sat Jul 22 13:28:31 CST 2023:hcp_fix: TrainingData: HCP_hp2000.RData
Sat Jul 22 13:28:31 CST 2023:hcp_fix: FixThresh: 10
Sat Jul 22 13:28:31 CST 2023:hcp_fix: DeleteIntermediates: FALSE
Sat Jul 22 13:28:31 CST 2023:hcp_fix: tr: 0.700000 
Sat Jul 22 13:28:31 CST 2023:hcp_fix: Running highpass
Sat Jul 22 13:28:38 CST 2023:hcp_fix: highpass_cmd: /usr/local/fsl/bin/fslmaths rfMRI_REST1_LR -sub rfMRI_REST1_LR_hp2000 -bptf 1428.5714285714 -1 -add rfMRI_REST1_LR_hp2000 rfMRI_REST1_LR_hp2000
Sat Jul 22 13:30:57 CST 2023:hcp_fix: Running MELODIC located at: /usr/local/fsl/bin/melodic
Sat Jul 22 13:30:57 CST 2023:hcp_fix: melodic_cmd: /usr/local/fsl/bin/melodic -i rfMRI_REST1_LR_hp2000 -o rfMRI_REST1_LR_hp2000.ica/filtered_func_data.ica --nobet --report --Oall --tr=0.700000 
Sat Jul 22 13:37:41 CST 2023:hcp_fix: melodic has been run: return_code = 0
Sat Jul 22 13:37:42 CST 2023:hcp_fix: Creating mc/prefiltered_func_data_mcf.par file
Sat Jul 22 13:37:48 CST 2023:hcp_fix: Running FIX
Sat Jul 22 13:37:48 CST 2023:hcp_fix: using training data file: /usr/local/fix/training_files/HCP_hp2000.RData
Sat Jul 22 13:37:48 CST 2023:hcp_fix: fix_cmd: /usr/local/fix/fix rfMRI_REST1_LR_hp2000.ica /usr/local/fix/training_files/HCP_hp2000.RData 10 -m -h 2000
Sat Jul 22 13:37:48 CST 2023:hcp_fix: Check rfMRI_REST1_LR_hp2000.ica/fix/logMatlab.txt for log output from feature extraction
Sat Jul 22 13:37:48 CST 2023:hcp_fix: Check rfMRI_REST1_LR_hp2000.ica/.fix_2b_predict.log for log output from component classification
Sat Jul 22 13:37:48 CST 2023:hcp_fix: Check rfMRI_REST1_LR_hp2000.ica/.fix.log for log output from cleanup stage
FIX Feature extraction for Melodic output directory: rfMRI_REST1_LR_hp2000.ica
 create edge masks
 run FAST
 registration of standard space masks
 extract features
FIX Classifying components in Melodic directory: rfMRI_REST1_LR_hp2000.ica using training file: /usr/local/fix/training_files/HCP_hp2000.RData and threshold 10
FIX features not already generated, so creating them now.
FIX Feature extraction for Melodic output directory: rfMRI_REST1_LR_hp2000.ica
 create edge masks
 run FAST
 registration of standard space masks
 extract features
No valid labelling file specified
Sat Jul 22 13:48:09 CST 2023:hcp_fix: Done running FIX
Could not find a supported file with prefix "rfMRI_REST1_LR_hp2000.ica/filtered_func_data_clean"
Sat Jul 22 13:48:09 CST 2023:hcp_fix: ERROR: '/usr/local/fsl/bin/immv' command failed with return code: 1

===> ERROR: Command returned with nonzero exit code
---------------------------------------------------
         script: hcp_fix
stopped at line: 462
           call: $FSLDIR/bin/immv ${fmrihp}.ica/filtered_func_data_clean ${fmrihp}_clean
  expanded call: /usr/local/fsl/bin/immv rfMRI_REST1_LR_hp2000.ica/filtered_func_data_clean rfMRI_REST1_LR_hp2000_clean
      exit code: 1
---------------------------------------------------

===> Aborting execution!

I had checked error.log in file</MNINonLinear/Results/rfMRI_REST1_RL>, it said that:
Can't reload '/usr/local/MATLAB/MATLAB_Runtime/v93/bin/glnxa64/libmwcoder_types.so'

I installed Matlab compiler Runtime v93 recently, and set LD_LIBRARY_PATH properly. I also tried installing libxt6 libxcomposite1 libfontconfig1 libasound2 and update and it still did not work.

How to solve this problem?

Thank you very much for your time.

**Comment by glasserm** [comment] 2023-07-22 16:16
Are you trying to rerun the HCP young adult data or is this just a test to get things running?  We would recommend hp=0, no motion regression, and multi-run sICA+FIX these days.  I think this issue might have been solved on the HCP-Users mailing list archives.  The issue is with your specific computing environment, not the HCP Pipelines, so I am closing this.  You can get further help on HCP-Users.

**Closed by glasserm** 2023-07-22 16:16 UTC

**Comment by ContestantsD** [comment] 2024-10-13 12:47
Hi, betsy1226, did you fixed this problem? can you share with me? @betsy1226

**Comment by betsy1226** [comment] 2024-10-14 08:07
> Hi, betsy1226, did you fixed this problem? can you share with me? @betsy1226

I found if Ubuntu version was 20 or more, the error would occur.  To run this ICAFIX, make sure the Ubuntu version no more than 18 with Matlab 2017b.

**Comment by ContestantsD** [comment] 2024-10-14 08:10
> > Hi, betsy1226, did you fixed this problem? can you share with me? @betsy1226
> 
> I found if Ubuntu version was 20 or more, the error would occur. To run this ICAFIX, make sure the Ubuntu version no more than 18 with Matlab 2017b.

thank you very much！
